### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pepsimans** [Varulv1997/purplenitter#4]
thanks for your great job!
after deploy to heroku with [your link](https://heroku.com/deploy?template=https://github.com/Varulv1997/purplenitter/tree/heroku) its not working...
![image](https://user-images.githubusercontent.com/84022938/117819215-e9602780-b29b-11eb-8865-bcf2efb440ba.png)

**Comment by Varulv1997** [comment]
Hello there :)
Unfortunately I have stopped working on this as its useless..  
The Twitter API isn't accessible on Heroku, I believe Heroku is blacklisted.

As of now the "heroku" branch and button still exist, but will be removed.

I suggest you move on to an alternative like AWS for example.
